version: '3.8'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - 5000:8080
    container_name: rent-anything-backend
    networks:
      - prod
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mariadb:10.6.4
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    container_name: rent-anything-db
    networks:
      - prod
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 10

  debug:
    image: busybox
    container_name: debug-container
    tty: true
    networks:
      - prod


networks:
  prod:
    driver: bridge

volumes:
  db_data:
