spring:
  datasource:
    url: jdbc:mariadb://rent-anything-db:3306/rent_anything?useSSL=false
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    dbcp2:
      max-wait-millis: 30000
      validation-query: SELECT 1
      validation-query-timeout: 30
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
springdoc:
  pathsToMatch: /api/**

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate: DEBUG

users:
  initial:
    - username: admin
      password: admin
      email: admin@example.com
      firstName: Admin
      lastName: User
      canPostOffer: true
      role: ADMIN
    - username: poster
      password: poster
      email: poster@example.com
      firstName: Poster
      lastName: User
      canPostOffer: true
      role: POSTER
    - username: renter
      password: renter
      email: renter@example.com
      firstName: Renter
      lastName: User
      canPostOffer: false
      role: RENTER